"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { applyReview, isDue } from "@/lib/scheduler";
import { loadProgress, mergeProgress, saveProgress, seedCards, type Direction, type Progress } from "@/lib/data";
import { getSupabaseBrowserClient } from "@/lib/supabase-browser";
import { loadRemoteProgress, syncReview } from "@/lib/progress-sync";
import { loadCatalog } from "@/lib/catalog";
import { getCardImageUrl } from "@/lib/card-image";
export default function StudyPage(){
 const [index,setIndex]=useState(0); const [flipped,setFlipped]=useState(false); const [direction,setDirection]=useState<Direction>("en-uk"); const [progress,setProgress]=useState<Progress[]>([]); const [cards,setCards]=useState(seedCards); const [syncMessage,setSyncMessage]=useState(""); const card=useMemo(()=>cards[index%cards.length]??seedCards[0],[cards,index]);
 useEffect(()=>{let active=true;const initialize=async()=>{const local=loadProgress();let availableProgress=local;const supabase=getSupabaseBrowserClient();if(supabase){const{data}=await supabase.auth.getUser();if(data.user){try{const remote=await loadRemoteProgress(data.user.id);if(remote.length){availableProgress=mergeProgress(local,remote);saveProgress(availableProgress)}}catch(error){console.error("Remote progress load failed",error)}}}let selectedCardIds:string[]=[];let selectedThemes:string[]=[];try{selectedCardIds=JSON.parse(localStorage.getItem("wordly-selected-cards-v1")??"[]");selectedThemes=JSON.parse(localStorage.getItem("wordly-selected-v1")??"[]")}catch{}const{cards:catalogCards}=await loadCatalog();const selectedPool=selectedCardIds.length?catalogCards.filter(item=>selectedCardIds.includes(item.id)):selectedThemes.length?catalogCards.filter(item=>selectedThemes.includes(item.theme)):catalogCards;const pool=selectedPool.length?selectedPool:catalogCards;const dueCards=pool.filter(item=>{const itemProgress=availableProgress.filter(entry=>entry.cardId===item.id);return itemProgress.length===0||itemProgress.some(entry=>!entry.learned&&isDue(entry))});if(active){setProgress(availableProgress);setCards(dueCards.length?dueCards:pool)}};void initialize();return()=>{active=false}},[]);
 const speakEnglish=useCallback(()=>{if(typeof window!=="undefined"){const u=new SpeechSynthesisUtterance(card.en);u.lang="en-US";window.speechSynthesis.cancel();window.speechSynthesis.speak(u)}},[card.en]);
 useEffect(()=>{if(direction!=="en-uk")return;const timer=window.setTimeout(speakEnglish,120);return()=>window.clearTimeout(timer)},[card.id,direction,speakEnglish]);
 const review=async(known:boolean)=>{const current=progress.find(p=>p.cardId===card.id&&p.direction===direction);const next=applyReview(current,card.id,direction,known);const other=progress.find(p=>p.cardId===card.id&&p.direction!==direction);next.learned=next.successCount>=2&&(other?.successCount??0)>=2;const updated=[...progress.filter(p=>!(p.cardId===card.id&&p.direction===direction)),next];setProgress(updated);saveProgress(updated);const supabase=getSupabaseBrowserClient();if(!supabase){setSyncMessage("Локальний режим: Supabase не підключено")}else{const{data,error:authError}=await supabase.auth.getUser();if(authError||!data.user){setSyncMessage("Увійдіть через email, щоб синхронізувати прогрес")}else{try{await syncReview(data.user.id,card.id,direction,known,next);setSyncMessage("")}catch(error){console.error("Supabase progress sync failed",error);const details=typeof error==="object"&&error!==null&&"message" in error?String(error.message):"Невідома помилка Supabase";const code=typeof error==="object"&&error!==null&&"code" in error?` [код ${String(error.code)}]`:"";setSyncMessage(`Помилка синхронізації: ${details}${code}`)}}}setDirection(known?(direction==="en-uk"?"uk-en":"en-uk"):direction);setIndex(index+1);setFlipped(false)};
 const current=progress.find(p=>p.cardId===card.id&&p.direction===direction);
 const englishVisible=(direction==="en-uk"&&!flipped)||(direction==="uk-en"&&flipped);
 return <div className="study-layout"><div className="eyebrow">Сесія на сьогодні</div><h2>Тримай ритм</h2><div className="study-meta"><span>{index+1} з {cards.length} карток на повторення</span><span>{current?.successCount??0}/2 у цьому напрямку</span></div><div className="flashcard" onClick={()=>setFlipped(!flipped)}><img className="study-card-image" src={getCardImageUrl(card)} alt={`Ілюстрація до ${card.en}`} fetchPriority="high" /><div className="word">{flipped?(direction==="en-uk"?card.uk:card.en):(direction==="en-uk"?card.en:card.uk)}</div>{flipped?<><div className="translation">{direction==="en-uk"?card.en:card.uk}</div><div className="hint">{card.example}</div></>:<div className="hint">Натисни, щоб перевернути</div>}</div><div className="actions">{flipped&&<button className="swipe no" onClick={()=>review(false)} aria-label="Ще не знаю">←</button>}{englishVisible&&<button className="button secondary" onClick={speakEnglish}>🔊 Прослухати англійською</button>}{flipped&&<button className="swipe yes" onClick={()=>review(true)} aria-label="Знаю">→</button>}</div>{syncMessage&&<p role="status" style={{color:"#9a3412"}}>{syncMessage}</p>}<p>Ліворуч — повторити. Праворуч — знаю. Прогрес зберігається у браузері.</p><Link href="/" className="eyebrow">← До прогресу</Link></div>;
}


